"""Compatibility exports for API schemas.

New code should import from the owning module (for example,
``app.schemas.papers``) so parallel feature branches do not edit this file.
"""

from app.schemas.common import HealthRead
from app.schemas.papers import PaperDocumentRead, WorkspacePaperPage
from app.schemas.projects import ProjectCreate, ProjectRead
from app.schemas.repositories import (
    CodeRepositoryRead,
    WorkspaceCodeFileRead,
    WorkspaceCodeFileSaveResult,
    WorkspaceCodeFileSummary,
    WorkspaceCodeFileUpdate,
    WorkspaceCodeTreeNode,
    WorkspaceTensorFlowEdge,
    WorkspaceTensorFlowNode,
    WorkspaceTensorFlowRead,
)
from app.schemas.traces import (
    TraceLinkCreate,
    TraceLinkRead,
    TraceLinkSuggestion,
    WorkspaceTraceRow,
)
from app.schemas.workspace import (
    WorkspaceAnalyzeJob,
    WorkspaceAnalyzeRequest,
    WorkspaceConflictItem,
    WorkspaceFlowNode,
    WorkspaceImportStep,
    WorkspaceRead,
    WorkspaceReportCard,
)

__all__ = [
    "CodeRepositoryRead",
    "HealthRead",
    "PaperDocumentRead",
    "ProjectCreate",
    "ProjectRead",
    "TraceLinkCreate",
    "TraceLinkRead",
    "TraceLinkSuggestion",
    "WorkspaceAnalyzeJob",
    "WorkspaceAnalyzeRequest",
    "WorkspaceCodeFileRead",
    "WorkspaceCodeFileSaveResult",
    "WorkspaceCodeFileSummary",
    "WorkspaceCodeFileUpdate",
    "WorkspaceCodeTreeNode",
    "WorkspaceConflictItem",
    "WorkspaceFlowNode",
    "WorkspaceImportStep",
    "WorkspacePaperPage",
    "WorkspaceRead",
    "WorkspaceReportCard",
    "WorkspaceTensorFlowEdge",
    "WorkspaceTensorFlowNode",
    "WorkspaceTensorFlowRead",
    "WorkspaceTraceRow",
]
