/** Desktop-aligned Chinese UI strings for the VS Code extension. */
export const zh = {
  workbench: '工作台',
  tensorFlow: '张量流图',
  workflow: '工作流',
  init: '初始化',
  importPdf: '导入论文',
  parsePaper: '解析论文',
  analyzeCode: '分析代码',
  generateTrace: '生成追溯',
  openPaper: '论文',
  openMatrix: '追溯矩阵',
  openTensor: '张量流图',
  refresh: '刷新',
  configureMineru: '配置 MinerU',
  configureLlm: '配置 LLM',
  showOutput: '显示输出',
  llmSection: 'LLM（Agent）',
  mineruSection: 'MinerU',
  saveLlm: '保存 LLM',
  saveMineru: '保存 MinerU',
  clearLlmKey: '清除 API Key',
  clearMineruToken: '清除 Token',
  probeLlm: '测试连通性',
  probeMineru: '测试连通性',
  baseUrl: 'Base URL',
  model: '模型',
  thinkingMode: '思考模式',
  timeout: '超时（秒）',
  apiKey: 'API Key',
  apiToken: 'API Token',
  provider: '提供方',
  language: '语言',
  requestTimeout: '请求超时（秒）',
  taskTimeout: '任务超时（秒）',
  keyConfigured: '已配置 — 留空则保留',
  keyMissing: '未配置',
  tokenConfigured: '已配置 — 留空则保留',
  tokenMissing: '未配置',
  settingsSaved: '设置已保存（密钥仅在输入新值时更新）',
  keyCleared: '密钥已清除',
  openFolderFirst: '请先打开工作区文件夹',
  artifactsRoot: '产物目录',
  paperReady: '论文已解析',
  paperMissing: '等待论文',
  codeReady: '仓库已分析',
  codeMissing: '等待本地分析',
  pdfImported: '已导入',
  pdfNone: '无',
  analysisLog: '分析日志',
  markdown: 'Markdown',
  pdfOriginal: 'PDF 原件',
  outline: '大纲',
  noSections: '暂无章节',
  openCode: '打开代码',
  locatePaper: '定位论文',
  accept: '接受',
  reject: '拒绝',
  reset: '重置',
  architecture: '架构',
  debug: '调试',
  back: '返回',
  fit: '适应画布',
  zoomIn: '放大',
  zoomOut: '缩小',
  selectRoot: '选择主模型',
  tensorHint: '滚轮缩放 · 拖动画布 · 单击跳转代码 · 双击带 + 的模块下钻',
  tensorEmpty: '当前层无节点。请先分析含 PyTorch 的项目，再选择主模型。',
  runAnalyzeFirst: '张量流失败 — 请先运行「分析代码」',
  noPdf: '尚未导入 source.pdf — 请先导入论文 PDF',
  noMarkdown: '尚无 Markdown — 请先运行「解析论文」',
  paperTitle: 'TraceLab 论文',
  matrixTitle: 'TraceLab 追溯矩阵',
  tensorTitle: 'TraceLab 张量流图',
} as const
