"""server_baseline"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '0001_server_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False)
    op.create_table('auth_rate_limit',
    sa.Column('bucket_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('window_started_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bucket_key')
    )
    op.create_table('background_job',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_background_job_idempotency')
    )
    op.create_index(op.f('ix_background_job_available_at'), 'background_job', ['available_at'], unique=False)
    op.create_index(op.f('ix_background_job_job_type'), 'background_job', ['job_type'], unique=False)
    op.create_index(op.f('ix_background_job_lease_expires_at'), 'background_job', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_background_job_status'), 'background_job', ['status'], unique=False)
    op.create_index(op.f('ix_background_job_workspace_id'), 'background_job', ['workspace_id'], unique=False)
    op.create_table('blob_content',
    sa.Column('content_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('physical_ref_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_blob_content_sha256'), 'blob_content', ['sha256'], unique=True)
    op.create_table('user_account',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('email_normalized', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_account_email_normalized'), 'user_account', ['email_normalized'], unique=True)
    op.create_index(op.f('ix_user_account_is_platform_admin'), 'user_account', ['is_platform_admin'], unique=False)
    op.create_index(op.f('ix_user_account_status'), 'user_account', ['status'], unique=False)
    op.create_table('admin_web_session',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('csrf_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_admin_web_session_expires_at'), 'admin_web_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_admin_web_session_token_hash'), 'admin_web_session', ['token_hash'], unique=True)
    op.create_index(op.f('ix_admin_web_session_user_id'), 'admin_web_session', ['user_id'], unique=False)
    op.create_table('device',
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('client_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_device_last_seen_at'), 'device', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_device_user_id'), 'device', ['user_id'], unique=False)
    op.create_table('email_token',
    sa.Column('token_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_email_token_expires_at'), 'email_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_token_purpose'), 'email_token', ['purpose'], unique=False)
    op.create_index(op.f('ix_email_token_user_id'), 'email_token', ['user_id'], unique=False)
    op.create_table('workspace',
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('storage_limit_bytes', sa.BigInteger(), nullable=False),
    sa.Column('workspace_seq', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index(op.f('ix_workspace_created_by'), 'workspace', ['created_by'], unique=False)
    op.create_table('auth_session',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('previous_refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_ip_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_agent_summary', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_auth_session_device_id'), 'auth_session', ['device_id'], unique=False)
    op.create_index(op.f('ix_auth_session_expires_at'), 'auth_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_session_refresh_token_hash'), 'auth_session', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_auth_session_revoked_at'), 'auth_session', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_session_user_id'), 'auth_session', ['user_id'], unique=False)
    op.create_table('blob_object',
    sa.Column('blob_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('project_public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('content_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['blob_content.content_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('blob_id'),
    sa.UniqueConstraint('workspace_id', 'sha256', name='uq_blob_workspace_hash')
    )
    op.create_index(op.f('ix_blob_object_content_id'), 'blob_object', ['content_id'], unique=False)
    op.create_index(op.f('ix_blob_object_project_public_id'), 'blob_object', ['project_public_id'], unique=False)
    op.create_index(op.f('ix_blob_object_sha256'), 'blob_object', ['sha256'], unique=False)
    op.create_index(op.f('ix_blob_object_status'), 'blob_object', ['status'], unique=False)
    op.create_index(op.f('ix_blob_object_workspace_id'), 'blob_object', ['workspace_id'], unique=False)
    op.create_table('cloud_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=72), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('project_public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'entity_type', 'public_id', name='uq_cloud_entity')
    )
    op.create_index(op.f('ix_cloud_entity_deleted_at'), 'cloud_entity', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cloud_entity_entity_type'), 'cloud_entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_cloud_entity_project_public_id'), 'cloud_entity', ['project_public_id'], unique=False)
    op.create_index(op.f('ix_cloud_entity_public_id'), 'cloud_entity', ['public_id'], unique=False)
    op.create_index(op.f('ix_cloud_entity_workspace_id'), 'cloud_entity', ['workspace_id'], unique=False)
    op.create_table('cloud_project',
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sync_mode', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('agent_history_sync', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_index(op.f('ix_cloud_project_deleted_at'), 'cloud_project', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cloud_project_sync_mode'), 'cloud_project', ['sync_mode'], unique=False)
    op.create_index(op.f('ix_cloud_project_workspace_id'), 'cloud_project', ['workspace_id'], unique=False)
    op.create_table('device_project_binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('project_public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sync_mode', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'project_public_id', name='uq_device_project_binding')
    )
    op.create_index(op.f('ix_device_project_binding_device_id'), 'device_project_binding', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_project_binding_project_public_id'), 'device_project_binding', ['project_public_id'], unique=False)
    op.create_index(op.f('ix_device_project_binding_sync_mode'), 'device_project_binding', ['sync_mode'], unique=False)
    op.create_index(op.f('ix_device_project_binding_workspace_id'), 'device_project_binding', ['workspace_id'], unique=False)
    op.create_table('entity_tombstone',
    sa.Column('tombstone_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_public_id', sqlmodel.sql.sqltypes.AutoString(length=72), nullable=False),
    sa.Column('deleted_version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('tombstone_id'),
    sa.UniqueConstraint('workspace_id', 'entity_type', 'entity_public_id', name='uq_entity_tombstone')
    )
    op.create_index(op.f('ix_entity_tombstone_entity_public_id'), 'entity_tombstone', ['entity_public_id'], unique=False)
    op.create_index(op.f('ix_entity_tombstone_entity_type'), 'entity_tombstone', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_tombstone_expires_at'), 'entity_tombstone', ['expires_at'], unique=False)
    op.create_index(op.f('ix_entity_tombstone_workspace_id'), 'entity_tombstone', ['workspace_id'], unique=False)
    op.create_table('sync_device_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('last_pulled_seq', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'workspace_id', name='uq_sync_device_cursor')
    )
    op.create_index(op.f('ix_sync_device_cursor_device_id'), 'sync_device_cursor', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_device_cursor_workspace_id'), 'sync_device_cursor', ['workspace_id'], unique=False)
    op.create_table('sync_event',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_seq', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_public_id', sqlmodel.sql.sqltypes.AutoString(length=72), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('entity_version', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('workspace_id', 'workspace_seq', name='uq_sync_workspace_seq')
    )
    op.create_index(op.f('ix_sync_event_created_at'), 'sync_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_event_entity_public_id'), 'sync_event', ['entity_public_id'], unique=False)
    op.create_index(op.f('ix_sync_event_entity_type'), 'sync_event', ['entity_type'], unique=False)
    op.create_index(op.f('ix_sync_event_workspace_id'), 'sync_event', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_sync_event_workspace_seq'), 'sync_event', ['workspace_seq'], unique=False)
    op.create_table('sync_receipt',
    sa.Column('receipt_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('client_operation_id', sqlmodel.sql.sqltypes.AutoString(length=72), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('receipt_id'),
    sa.UniqueConstraint('client_operation_id', 'device_id', name='uq_sync_receipt_operation')
    )
    op.create_index(op.f('ix_sync_receipt_client_operation_id'), 'sync_receipt', ['client_operation_id'], unique=False)
    op.create_index(op.f('ix_sync_receipt_created_at'), 'sync_receipt', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_receipt_device_id'), 'sync_receipt', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_receipt_workspace_id'), 'sync_receipt', ['workspace_id'], unique=False)
    op.create_table('workspace_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_index(op.f('ix_workspace_member_role'), 'workspace_member', ['role'], unique=False)
    op.create_index(op.f('ix_workspace_member_user_id'), 'workspace_member', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_workspace_id'), 'workspace_member', ['workspace_id'], unique=False)
    op.create_table('artifact_version',
    sa.Column('version_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('project_public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('blob_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blob_id'], ['blob_object.blob_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('workspace_id', 'entity_type', 'entity_public_id', 'version_number', name='uq_artifact_version_number')
    )
    op.create_index(op.f('ix_artifact_version_blob_id'), 'artifact_version', ['blob_id'], unique=False)
    op.create_index(op.f('ix_artifact_version_deleted_at'), 'artifact_version', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_artifact_version_entity_public_id'), 'artifact_version', ['entity_public_id'], unique=False)
    op.create_index(op.f('ix_artifact_version_entity_type'), 'artifact_version', ['entity_type'], unique=False)
    op.create_index(op.f('ix_artifact_version_is_current'), 'artifact_version', ['is_current'], unique=False)
    op.create_index(op.f('ix_artifact_version_project_public_id'), 'artifact_version', ['project_public_id'], unique=False)
    op.create_index(op.f('ix_artifact_version_workspace_id'), 'artifact_version', ['workspace_id'], unique=False)
    op.create_table('upload_session',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('blob_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('uploaded_bytes', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['blob_object.blob_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_upload_session_blob_id'), 'upload_session', ['blob_id'], unique=True)
    op.create_index(op.f('ix_upload_session_expires_at'), 'upload_session', ['expires_at'], unique=False)
    op.create_table('blob_reference',
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('project_public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('artifact_version_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('blob_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_version.version_id'], ),
    sa.ForeignKeyConstraint(['blob_id'], ['blob_object.blob_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('reference_id'),
    sa.UniqueConstraint('workspace_id', 'project_public_id', 'entity_type', 'entity_public_id', 'blob_id', name='uq_blob_reference_target')
    )
    op.create_index(op.f('ix_blob_reference_artifact_version_id'), 'blob_reference', ['artifact_version_id'], unique=False)
    op.create_index(op.f('ix_blob_reference_blob_id'), 'blob_reference', ['blob_id'], unique=False)
    op.create_index(op.f('ix_blob_reference_deleted_at'), 'blob_reference', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_blob_reference_entity_public_id'), 'blob_reference', ['entity_public_id'], unique=False)
    op.create_index(op.f('ix_blob_reference_entity_type'), 'blob_reference', ['entity_type'], unique=False)
    op.create_index(op.f('ix_blob_reference_project_public_id'), 'blob_reference', ['project_public_id'], unique=False)
    op.create_index(op.f('ix_blob_reference_workspace_id'), 'blob_reference', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blob_reference_workspace_id'), table_name='blob_reference')
    op.drop_index(op.f('ix_blob_reference_project_public_id'), table_name='blob_reference')
    op.drop_index(op.f('ix_blob_reference_entity_type'), table_name='blob_reference')
    op.drop_index(op.f('ix_blob_reference_entity_public_id'), table_name='blob_reference')
    op.drop_index(op.f('ix_blob_reference_deleted_at'), table_name='blob_reference')
    op.drop_index(op.f('ix_blob_reference_blob_id'), table_name='blob_reference')
    op.drop_index(op.f('ix_blob_reference_artifact_version_id'), table_name='blob_reference')
    op.drop_table('blob_reference')
    op.drop_index(op.f('ix_upload_session_expires_at'), table_name='upload_session')
    op.drop_index(op.f('ix_upload_session_blob_id'), table_name='upload_session')
    op.drop_table('upload_session')
    op.drop_index(op.f('ix_artifact_version_workspace_id'), table_name='artifact_version')
    op.drop_index(op.f('ix_artifact_version_project_public_id'), table_name='artifact_version')
    op.drop_index(op.f('ix_artifact_version_is_current'), table_name='artifact_version')
    op.drop_index(op.f('ix_artifact_version_entity_type'), table_name='artifact_version')
    op.drop_index(op.f('ix_artifact_version_entity_public_id'), table_name='artifact_version')
    op.drop_index(op.f('ix_artifact_version_deleted_at'), table_name='artifact_version')
    op.drop_index(op.f('ix_artifact_version_blob_id'), table_name='artifact_version')
    op.drop_table('artifact_version')
    op.drop_index(op.f('ix_workspace_member_workspace_id'), table_name='workspace_member')
    op.drop_index(op.f('ix_workspace_member_user_id'), table_name='workspace_member')
    op.drop_index(op.f('ix_workspace_member_role'), table_name='workspace_member')
    op.drop_table('workspace_member')
    op.drop_index(op.f('ix_sync_receipt_workspace_id'), table_name='sync_receipt')
    op.drop_index(op.f('ix_sync_receipt_device_id'), table_name='sync_receipt')
    op.drop_index(op.f('ix_sync_receipt_created_at'), table_name='sync_receipt')
    op.drop_index(op.f('ix_sync_receipt_client_operation_id'), table_name='sync_receipt')
    op.drop_table('sync_receipt')
    op.drop_index(op.f('ix_sync_event_workspace_seq'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_workspace_id'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_entity_type'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_entity_public_id'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_created_at'), table_name='sync_event')
    op.drop_table('sync_event')
    op.drop_index(op.f('ix_sync_device_cursor_workspace_id'), table_name='sync_device_cursor')
    op.drop_index(op.f('ix_sync_device_cursor_device_id'), table_name='sync_device_cursor')
    op.drop_table('sync_device_cursor')
    op.drop_index(op.f('ix_entity_tombstone_workspace_id'), table_name='entity_tombstone')
    op.drop_index(op.f('ix_entity_tombstone_expires_at'), table_name='entity_tombstone')
    op.drop_index(op.f('ix_entity_tombstone_entity_type'), table_name='entity_tombstone')
    op.drop_index(op.f('ix_entity_tombstone_entity_public_id'), table_name='entity_tombstone')
    op.drop_table('entity_tombstone')
    op.drop_index(op.f('ix_device_project_binding_workspace_id'), table_name='device_project_binding')
    op.drop_index(op.f('ix_device_project_binding_sync_mode'), table_name='device_project_binding')
    op.drop_index(op.f('ix_device_project_binding_project_public_id'), table_name='device_project_binding')
    op.drop_index(op.f('ix_device_project_binding_device_id'), table_name='device_project_binding')
    op.drop_table('device_project_binding')
    op.drop_index(op.f('ix_cloud_project_workspace_id'), table_name='cloud_project')
    op.drop_index(op.f('ix_cloud_project_sync_mode'), table_name='cloud_project')
    op.drop_index(op.f('ix_cloud_project_deleted_at'), table_name='cloud_project')
    op.drop_table('cloud_project')
    op.drop_index(op.f('ix_cloud_entity_workspace_id'), table_name='cloud_entity')
    op.drop_index(op.f('ix_cloud_entity_public_id'), table_name='cloud_entity')
    op.drop_index(op.f('ix_cloud_entity_project_public_id'), table_name='cloud_entity')
    op.drop_index(op.f('ix_cloud_entity_entity_type'), table_name='cloud_entity')
    op.drop_index(op.f('ix_cloud_entity_deleted_at'), table_name='cloud_entity')
    op.drop_table('cloud_entity')
    op.drop_index(op.f('ix_blob_object_workspace_id'), table_name='blob_object')
    op.drop_index(op.f('ix_blob_object_status'), table_name='blob_object')
    op.drop_index(op.f('ix_blob_object_sha256'), table_name='blob_object')
    op.drop_index(op.f('ix_blob_object_project_public_id'), table_name='blob_object')
    op.drop_index(op.f('ix_blob_object_content_id'), table_name='blob_object')
    op.drop_table('blob_object')
    op.drop_index(op.f('ix_auth_session_user_id'), table_name='auth_session')
    op.drop_index(op.f('ix_auth_session_revoked_at'), table_name='auth_session')
    op.drop_index(op.f('ix_auth_session_refresh_token_hash'), table_name='auth_session')
    op.drop_index(op.f('ix_auth_session_expires_at'), table_name='auth_session')
    op.drop_index(op.f('ix_auth_session_device_id'), table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_index(op.f('ix_workspace_created_by'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_email_token_user_id'), table_name='email_token')
    op.drop_index(op.f('ix_email_token_purpose'), table_name='email_token')
    op.drop_index(op.f('ix_email_token_expires_at'), table_name='email_token')
    op.drop_table('email_token')
    op.drop_index(op.f('ix_device_user_id'), table_name='device')
    op.drop_index(op.f('ix_device_last_seen_at'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_admin_web_session_user_id'), table_name='admin_web_session')
    op.drop_index(op.f('ix_admin_web_session_token_hash'), table_name='admin_web_session')
    op.drop_index(op.f('ix_admin_web_session_expires_at'), table_name='admin_web_session')
    op.drop_table('admin_web_session')
    op.drop_index(op.f('ix_user_account_status'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_is_platform_admin'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email_normalized'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_blob_content_sha256'), table_name='blob_content')
    op.drop_table('blob_content')
    op.drop_index(op.f('ix_background_job_workspace_id'), table_name='background_job')
    op.drop_index(op.f('ix_background_job_status'), table_name='background_job')
    op.drop_index(op.f('ix_background_job_lease_expires_at'), table_name='background_job')
    op.drop_index(op.f('ix_background_job_job_type'), table_name='background_job')
    op.drop_index(op.f('ix_background_job_available_at'), table_name='background_job')
    op.drop_table('background_job')
    op.drop_table('auth_rate_limit')
    op.drop_index(op.f('ix_audit_log_workspace_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
